export const particleConfig = {
	key: 'particle',
	data: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAgAAAAICAYAAADED76LAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAD1JREFUeNpiYGBg2AvE/6H4ABSD2AeAeBcQ/4OC/0D8Foj/QAU2APEuJD4Yg9ggABLcCcWMUAwC26EYIMAATr8QrN+6EGUAAAAASUVORK5CYII='
};
